import os
ROOT = os.path.dirname(os.path.abspath(__file__))

SEED = 1
MIN_INTERACTIONS = 5
TEST_SIZE = 1 / 3
VIEW_PRODUCT_STRENGTH = 1
BUY_PRODUCT_STRENGTH = 3

EVAL_RANDOM_SAMPLE_NON_INTERACTED_ITEMS = 100

MIN_DF = 0.0
MAX_DF = 0.5
NGRAM_RANGE = (1, 3)
